---
version: '3.7'
services:
  app:
    image: "${DOCKER_ORGANIZATION}/${DOCKER_REPOSITORY}:${DOCKER_TAG}"
    environment:
      RAILS_LOG_TO_STDOUT: '1'
      RAILS_SERVE_STATIC_FILES: '1'
      WEB_PRELOAD_APP: '1'
      WEB_HEALTHCHECK_PATH: "/"
      DATABASE_URL: sqlite3:db/production.sqlite3
      HOST_UID:
      RAILS_ENV:
      SECRET_KEY_BASE:
      WEB_CONCURRENCY:
      WEB_TIMEOUT:
      WEB_WORKER_PROCESSES:
    ports:
    - "${PUBLISH_PORT:?PUBLISH_PORT must be provided}:8080"
    deploy:
      mode: replicated
      replicas: "${REPLICAS:-3}"
    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: '5'
    networks:
      local: {}
  rabbitmq:
    image: library/rabbitmq
    networks:
      local: {}
volumes: {}
networks:
  local:
    name: "${COMPOSE_PROJECT_NAME}"
