---
version: '3.7'
services:
  rabbitmq:
    image: library/rabbitmq
    ports:
    - "${sidecar-50488:}5672"
    networks:
      local: {}
volumes: {}
networks:
  local:
    name: "${COMPOSE_PROJECT_NAME}"
